-- 066: WWW Trainees — Basic Profile tab.
--
-- Phase 3 of the WWW backend.  Builds on:
--   064 — www_states / www_districts / www_centres
--   065 — www_areas / www_master_batches
--
-- Holds the Basic Profile tab of the Add Trainee form.  Tabs 2-11
-- (Family, Previous Employment, Financial Status, Housing & Asset
-- Info, Disability, Org Association, GBV, Reference, Commitment,
-- Review) will get their own related tables in later migrations.
--
-- Design summary
-- --------------
-- 1.  www_trainees — main row per trainee with single-value fields.
-- 2.  Three child tables for multi-value Basic-Profile data:
--       * www_trainee_emergency_contacts — variable number of phone numbers
--       * www_trainee_social_platforms   — multi-select platforms
--       * www_trainee_languages          — Language x Skill matrix
-- 3.  Single source-of-truth for geography: 4 FKs into the 064/065
--     tables.  ON UPDATE CASCADE / ON DELETE RESTRICT — admins can
--     rename codes; trainees can't be silently orphaned.
-- 4.  "Any other" -> a sibling _other VARCHAR column (cheaper to read
--     than a separate junction).
-- 5.  Soft delete via deleted_at everywhere.

SET search_path TO mis_azad, public;


-- ============================================================
-- 1) www_trainees — main Basic Profile row
-- ============================================================
CREATE TABLE IF NOT EXISTS www_trainees (
  id                       SERIAL PRIMARY KEY,
  enrollment_no            VARCHAR(50) UNIQUE,   -- auto-generated by backend
  photo_path               TEXT,                  -- relative path under uploads/

  -- ---------- Geography (FKs to 064 / 065 tables) ----------
  financial_year           VARCHAR(20),
  batch_id                 INT REFERENCES www_master_batches(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  state_code               VARCHAR(10) NOT NULL REFERENCES www_states(state_code)       ON UPDATE CASCADE ON DELETE RESTRICT,
  district_code            VARCHAR(20) NOT NULL REFERENCES www_districts(district_code) ON UPDATE CASCADE ON DELETE RESTRICT,
  centre_code              VARCHAR(20) NOT NULL REFERENCES www_centres(centre_code)     ON UPDATE CASCADE ON DELETE RESTRICT,
  area_code                VARCHAR(30)          REFERENCES www_areas(area_code)         ON UPDATE CASCADE ON DELETE RESTRICT,
  area_other               VARCHAR(200),   -- when area = "Any other"
  basti                    VARCHAR(200),

  -- ---------- Identity ----------
  name                     VARCHAR(200) NOT NULL,
  enrollment_date          DATE,
  enrollment_type          VARCHAR(20) CHECK (enrollment_type IN ('2 Wheeler', '4 Wheeler')),
  date_of_birth            DATE,
  age_at_enrollment        INT,        -- computed by backend on save
  blood_group              VARCHAR(10),
  mobile                   VARCHAR(15),
  email                    VARCHAR(150),
  current_address          TEXT,
  permanent_address        TEXT,

  -- ---------- Demographics (with -other specify text) ----------
  caste_category           VARCHAR(50),
  caste_other              VARCHAR(150),
  religion                 VARCHAR(50),
  religion_other           VARCHAR(150),
  gender                   VARCHAR(50),
  gender_other             VARCHAR(150),
  marital_status           VARCHAR(50),
  age_at_marriage          INT,
  living_with              VARCHAR(50),
  living_with_other        VARCHAR(150),

  -- ---------- Education ----------
  education_qualification  VARCHAR(50),
  education_other          VARCHAR(150),
  still_studying           BOOLEAN,
  studying_class           VARCHAR(50),

  -- ---------- Emergency contacts metadata (numbers in child table) ----------
  num_emergency_contacts   INT DEFAULT 0,

  -- ---------- Social media ----------
  has_social_media         BOOLEAN,

  -- ---------- Awareness ----------
  how_known_azad           VARCHAR(100),
  mobilization_activity    VARCHAR(100),

  -- ---------- License brought in by trainee ----------
  came_with_lic_type       VARCHAR(5) CHECK (came_with_lic_type IN ('LL', 'PL')),
  ll_date                  DATE,
  ll_number                VARCHAR(50),
  ll_attempts              INT,
  pl_date                  DATE,
  pl_number                VARCHAR(50),
  pl_attempts              INT,

  -- ---------- Lifecycle ----------
  status                   VARCHAR(30) DEFAULT 'Active'
                           CHECK (status IN ('Active', 'Walkout', 'Placed', 'Inactive')),

  -- ---------- Audit ----------
  created_by               INT,
  created_at               TIMESTAMPTZ DEFAULT NOW(),
  updated_at               TIMESTAMPTZ DEFAULT NOW(),
  deleted_at               TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_www_trainees_state      ON www_trainees(state_code);
CREATE INDEX IF NOT EXISTS idx_www_trainees_district   ON www_trainees(district_code);
CREATE INDEX IF NOT EXISTS idx_www_trainees_centre     ON www_trainees(centre_code);
CREATE INDEX IF NOT EXISTS idx_www_trainees_area       ON www_trainees(area_code);
CREATE INDEX IF NOT EXISTS idx_www_trainees_batch      ON www_trainees(batch_id);
CREATE INDEX IF NOT EXISTS idx_www_trainees_status     ON www_trainees(status);
CREATE INDEX IF NOT EXISTS idx_www_trainees_deleted_at ON www_trainees(deleted_at);
CREATE INDEX IF NOT EXISTS idx_www_trainees_name_lower ON www_trainees(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_www_trainees_mobile     ON www_trainees(mobile);


-- ============================================================
-- 2) www_trainee_emergency_contacts (variable rows)
-- ============================================================
CREATE TABLE IF NOT EXISTS www_trainee_emergency_contacts (
  trainee_id   INT NOT NULL REFERENCES www_trainees(id) ON UPDATE CASCADE ON DELETE CASCADE,
  seq          INT NOT NULL,
  contact_no   VARCHAR(20) NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (trainee_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_www_trainee_emg_trainee ON www_trainee_emergency_contacts(trainee_id);


-- ============================================================
-- 3) www_trainee_social_platforms (multi-select)
-- ============================================================
CREATE TABLE IF NOT EXISTS www_trainee_social_platforms (
  trainee_id   INT NOT NULL REFERENCES www_trainees(id) ON UPDATE CASCADE ON DELETE CASCADE,
  platform     VARCHAR(30) NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (trainee_id, platform)
);
CREATE INDEX IF NOT EXISTS idx_www_trainee_social_trainee ON www_trainee_social_platforms(trainee_id);


-- ============================================================
-- 4) www_trainee_languages (Language x Skill matrix)
-- ============================================================
-- One row per (trainee, language).  The form lets each skill column
-- be ticked independently — matches the Basic-Profile language table.
CREATE TABLE IF NOT EXISTS www_trainee_languages (
  trainee_id      INT NOT NULL REFERENCES www_trainees(id) ON UPDATE CASCADE ON DELETE CASCADE,
  language        VARCHAR(30) NOT NULL,
  can_understand  BOOLEAN DEFAULT FALSE,
  can_speak       BOOLEAN DEFAULT FALSE,
  can_read        BOOLEAN DEFAULT FALSE,
  can_write       BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (trainee_id, language)
);
CREATE INDEX IF NOT EXISTS idx_www_trainee_lang_trainee ON www_trainee_languages(trainee_id);
